# PYTORCH FUNDAMENTALS

### Creating matrices

In [1]:
arr = [[2,3],[5,6]]
print(arr)

[[2, 3], [5, 6]]


In [2]:
import numpy as np
np.array(arr)

array([[2, 3],
       [5, 6]])

In [22]:
import torch 
print(torch.__version__)

0.4.0


In [7]:
ten = torch.Tensor(arr)
print(ten)
print(type(ten))

tensor([[ 2.,  3.],
        [ 5.,  6.]])
<class 'torch.Tensor'>


### Matrices with default values

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
torch.ones((2,2))

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [17]:
np.random.rand(3,2)

array([[0.43758721, 0.891773  ],
       [0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [14]:
torch.rand(3,2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320],
        [ 0.3074,  0.6341]])

In [15]:
# seeding random initializer
np.random.seed(0)
torch.manual_seed(0)

In [18]:
# seeding gpu randomizer
if torch.cuda.is_available():
    print("seeded GPU")
    torch.cuda.manual_seed_all(0)

seeded GPU


### Torch numpy bridge

In [25]:
np_arr = np.ones((2,2))
print(type(np_arr))

<class 'numpy.ndarray'>


In [27]:
# The only supported types of ndarray are: double, float, float16, int64, int32, and uint8
torch_tensor = torch.from_numpy(np_arr)
print(type(torch_tensor))

<class 'torch.Tensor'>


In [30]:
# converting back torch tensor to numpy array
np_arr = torch_tensor.numpy()
print(type(np_arr))

<class 'numpy.ndarray'>


### Toggle tensors between CPU and GPU

In [31]:
# by default all tensors are created on cpu
tensor_cpu = torch.ones((2,2))

In [32]:
# CPU to GPU
if torch.cuda.is_available():
    print("tensor now in GPU")
    tensor_cpu.cuda()

tensor now in GPU


In [34]:
# GPU to CPU
tensor_cpu.cpu()

tensor([[ 1.,  1.],
        [ 1.,  1.]])

### Tensor Operations

In [36]:
a = torch.ones(2,2)
print(a)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [46]:
# RESHAPING
# pass shape of tensor in view()
print(a.size())
a = a.view([4,1])
print(a)

torch.Size([4, 1])
tensor([[ 1.],
        [ 1.],
        [ 1.],
        [ 1.]])


In [63]:
# ADDITION,MULTIPLICATION,DIVISION AND SUBTRACTION
a = torch.ones(2,2)
b = torch.ones(2,2)
print("Sum : \n" +str(a.add(b)))
print("Diff : \n" +str(a.sub(b)))
print("Div : \n" +str(a.div(b)))
print("Mul : \n" +str(torch.mul(a,b)))
print("MatMul : \n" +str(torch.matmul(a,b)))

Sum : 
tensor([[ 2.,  2.],
        [ 2.,  2.]])
Diff : 
tensor([[ 0.,  0.],
        [ 0.,  0.]])
Div : 
tensor([[ 1.,  1.],
        [ 1.,  1.]])
Mul : 
tensor([[ 1.,  1.],
        [ 1.,  1.]])
MatMul : 
tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [64]:
# none of the above methods change the actual parameter to do that we use inplace operations
# all these methods end with "_"
a.sub(b)
print(a)               # without inplace
print(a.sub_(b))       # with inplace

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 0.,  0.],
        [ 0.,  0.]])


In [69]:
# MEAN AND STANDARD DEVIATION
a  = torch.Tensor([[1,2,3,4,5,6,7],[2,3,4,5,6,7,8]])
a.size()

torch.Size([2, 7])

In [72]:
print("Mean :")
print(a.mean(dim =0))
print(a.mean(dim =1))
print("\nStandard deviation :")
print(a.std(dim =0))
print(a.std(dim =1))

Mean :
tensor([ 1.5000,  2.5000,  3.5000,  4.5000,  5.5000,  6.5000,  7.5000])
tensor([ 4.,  5.])

Standard deviation :
tensor([ 0.7071,  0.7071,  0.7071,  0.7071,  0.7071,  0.7071,  0.7071])
tensor([ 2.1602,  2.1602])


### Variables

In [73]:
from torch.autograd import Variable

In [80]:
# all operations remain same as above tensors
a = Variable(torch.ones(2,2),requires_grad = True)
print(a)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [89]:
# the reason for having variables is to accumulate gradients

x = Variable(torch.ones(2),requires_grad = True)
y = 5 * (x + 1) ** 2
o = y.mean()
# backward function can only be called on scalar
o.backward(torch.Tensor([1,1]))
x.grad

tensor([ 10.,  10.])